### ISSUE TITLE
Navigation panel

### ISSUE THREAD

**Issue by vp393001** [microsoft/HealthBotContainerSample#10]
How to open navigation panel and get APP_SECRET & WEBCHAT_SECRET?

**Comment by AdamWalkerMicrosoft** [comment]
In your Healthcare Bot Management portal navigate to Integration > Secrets > Webchat secret. 

![image](https://user-images.githubusercontent.com/40535367/75245504-84bfc680-57d6-11ea-93bc-faec90c9ae4b.png)
