### ISSUE TITLE
No users are currently waiting for an agent.

### ISSUE THREAD

**Issue by vikramhn** [microsoft/HealthBotContainerSample#100]
I have followed all the steps for handoff.  When i am on the /agent.html, It lists the 
Current Conversations

    User ce36 is chatting with the bot [Conversation history]

Clicking connect states that - No users are currently waiting for an agent.

![image](https://user-images.githubusercontent.com/17201365/116611978-fd537300-a904-11eb-959f-02f71c442221.png)
Any ideas?

**Comment by vikramhn** [comment]
![image](https://user-images.githubusercontent.com/17201365/116612152-30960200-a905-11eb-90dc-4867aa3e3505.png)

**Comment by vikramhn** [comment]
![image](https://user-images.githubusercontent.com/17201365/116612190-3d1a5a80-a905-11eb-9720-53b04c5a3092.png)

**Comment by AdamWalkerMicrosoft** [comment]
Hi, Note that User CE36 is "Chatting with the bot". The End user need to move to the state of "Waiting for an agent". In the Health Bot scenario, you need to trigger the built-in Handoff scenario to move that agent state. See this part of the docs: https://docs.microsoft.com/en-us/azure/health-bot/handoff#conversation-context

**Comment by vikramhn** [comment]
Thanks Adam. #69 and also information from https://techcommunity.microsoft.com/t5/healthcare-and-life-sciences/updated-on-1-06-2021-quick-start-setting-up-your-covid-19/ba-p/1230537 helped resolve it.
