### ISSUE TITLE
Oops. Something went wrong and we need to start over.

### ISSUE THREAD

**Issue by gjlisiak** [microsoft/HealthBotContainerSample#103]
Health Bot Scenarios are using numerous Adaptive Cards (v1.2).  If the Adaptive Card is left blank and the user hits continue, the "Oops. Something went wrong and we need to start over." message is returned and the bot scenario ends.

Upon investigation, it appears that line 20 in the index.html file is the culprit.

    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"></script>

Upon changing this to reference an older js library, the issue goes away.  

     <script src="https://cdn.botframework.com/botframework-webchat/4.11.0/webchat-es5.js"></script>

**Comment by einatgruda** [comment]
> Health Bot Scenarios are using numerous Adaptive Cards (v1.2). If the Adaptive Card is left blank and the user hits continue, the "Oops. Something went wrong and we need to start over." message is returned and the bot scenario ends.
> 
> Upon investigation, it appears that line 20 in the index.html file is the culprit.
> 
> ```
> <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"></script>
> ```
> 
> Upon changing this to reference an older js library, the issue goes away.
> 
> ```
>  <script src="https://cdn.botframework.com/botframework-webchat/4.11.0/webchat-es5.js"></script>
> ```

Hi @gjlisiak , we are investigating this. Can you please let me know some more details (send me the scenario perhaps) as I could not easily reproduce? Thank you.

**Comment by amir-microsoft** [comment]
closing this issue has it been stale for 6 months with a response from the reporter
