### ISSUE TITLE
The healthbot userid and conversation id seem to be encrypted in application insights

### ISSUE THREAD

**Issue by xtianus79** [microsoft/HealthBotContainerSample#108]
https://docs.microsoft.com/en-us/azure/health-bot/custom_telemetry

We are using the directline npm package on our frontend and initiating the healthbot. 

The user id we set is not persisting through to application insights. it seems to be encrypted there. 

Is there a way to decrypt the convId and the userId so that we can reference data in application insights

**Comment by AdamWalkerMicrosoft** [comment]
Hi, The User ID is hashed on the Health Bot service side for privacy reasons. It helps to keep the end-user data pseudo-anonymous on the Microsoft side. 

Instead, consider passing a custom variable (with a unique identifier) when the scenario is invoked. This variable is accessible in the scenario args and you can send it through with a custom logging event. You can find more information in the following docs: 

https://docs.microsoft.com/en-us/azure/health-bot/integrations/programmatic_invocation
https://docs.microsoft.com/en-us/azure/health-bot/custom_telemetry
