### ISSUE TITLE
Unhandled rejection RangeError

### ISSUE THREAD

**Issue by HardikaDoshi** [microsoft/HealthBotContainerSample#109]
Hi,
I have cloned the repo and set the environment variables for `APP_SECRET` and `WEBCHAT_SECRET`.
When I run `npm start` I see the error

`Unhandled rejection RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:275:11)
    at ServerResponse._implicitHeader (node:_http_server:266:8)
    at ServerResponse.end (node:_http_outgoing:868:10)`

Details -
Windows 10 OS
Node version - 16.6.2
Npm version -7.20.3

**Comment by amir-microsoft** [comment]
hello @HardikaDoshi, maybe this was a transient tissue? is this issue still happening?
Can you please provide the resource name of the Azure Health Bot you are using?

**Comment by HardikaDoshi** [comment]
@amir-microsoft 
I am getting the same error.
My resource name is `azure-healthbot-401`

**Comment by amir-microsoft** [comment]
@HardikaDoshi, I just checked your bot and it seems to be working fine. 

Are you testing it on your local machine?
if that's the case, maybe some networking issue in your environment?
I would suggest to test it in an Azure environment (you can use the "Deploy to Azure" option from the readme of this project).
Another option to check if you are using your local machine is to make sure the APP_SECRET and WEBCHAT_SECRET are indeed available in the app and have the correct value by using the debugger.

**Comment by HardikaDoshi** [comment]
@amir-microsoft, yes I'm testing locally. 
As for `APP_SECRET` and `WEBCHAT_SECRET`, I've tried 

1. setting them as environment variables 
2. directly assigning the values in `server.js` and checking the console logs

**Comment by amir-microsoft** [comment]
I see.
can you try my suggestion to test on Azure to rule out any local networking issue on your local environment?

**Comment by HardikaDoshi** [comment]
@amir-microsoft, I've tested on azure, the bot works fine.

**Comment by amir-microsoft** [comment]
closing the issue as it works on Azure and probably related to an issue on @HardikaDoshi local environment
