### ISSUE TITLE
Enabling Handoff functionality

### ISSUE THREAD

**Issue by vp393001** [microsoft/HealthBotContainerSample#11]
The [Handoff to live agent documentation](https://docs.microsoft.com/en-us/healthbot/handoff?source=docs) says 

> Handoff functionality is disabled by default. To use this feature activate handoff from your management portal. Navigate to Configuration > Conversation > Human handoff and enable handoff.

I am unable to find out how to open the management portal.

**Comment by AdamWalkerMicrosoft** [comment]
If you have already created a Healthcare Bot from the Azure marketplace, you can access your instance by navigating to https://admin.healthbot.microsoft.com/

If you need to create a new Healthcare Bot you can create it by following steps on the marketplace listing here: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft-hcb.microsofthealthcarebot?tab=Overview
