### ISSUE TITLE
Unable to Handle the request - HTTP ERROR 500

### ISSUE THREAD

**Issue by LakshmiSweatha** [microsoft/HealthBotContainerSample#111]
After deployment facing this error(sometimes it works fine and within 1-2days facing error).
Application has thrown an uncaught exception and is terminated:
SyntaxError: Unexpected token ILLEGAL
at Module._compile (module.js:434:25)
at Object..js (module.js:464:10)
at Module.load (module.js:353:31)
at Function._load (module.js:311:12)
at Module.require (module.js:359:17)
at require (module.js:375:17)
at Object.<anonymous> (C:\Program Files (x86)\iisnode\interceptor.js:459:1)
at Module._compile (module.js:446:26)
at Object..js (module.js:464:10)
at Module.load (module.js:353:31)

Please provide solution asap.

**Comment by amir-microsoft** [comment]
Thanks for reporting @LakshmiSweatha!
There was indeed an issue with deploying the to Windows App Service on Azure: the nodeJS runtime was set in the deployment to a version that is no longer available on App Service Windows.
We've changed the deployment template to use version 16.13.0, so you should be fine with new deployments.
If you like to fix an existing deployment, you can change the Environment variable with key: "WEBSITE_NODE_DEFAULT_VERSION", to have the value: "16.13.0".

I hope that helps

**Comment by LakshmiSweatha** [comment]
> Thanks for reporting @LakshmiSweatha! There was indeed an issue with deploying to Windows App Service on Azure: the nodeJS runtime was set in the deployment to a version that is no longer available on App Service Windows. We've changed the deployment template to use version 16.13.0, so you should be fine with new deployments. If you like to fix an existing deployment, you can change the Environment variable with key: "WEBSITE_NODE_DEFAULT_VERSION", to have the value: "16.13.0".
> 
> I hope that helps

Hii
The issue got resolved. Thank you for the quick reply.
