### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by vp393001** [microsoft/HealthBotContainerSample#12]
I deployed the bot using **Deploy to Azure** button available at https://github.com/Microsoft/HealthBotContainerSample/tree/live_agent_handoff.

Then I opened xxxxx.azurewebsites.net URL but it says 403 Forbidden. The page doesn't display anything.

**Comment by AdamWalkerMicrosoft** [comment]
Hi, You need to provide the Application and Webchat Secrets from your Healthcare Bot Instance. These secrets associate the Webchat application with your specific bot.
