### ISSUE TITLE
How to customize design?

### ISSUE THREAD

**Issue by cihadturhan** [microsoft/HealthBotContainerSample#124]
We'd like to match the UI with our company design.
I see styles are loaded over remote service.

What's the best way to customize design?
Thanks

**Comment by GuyBeckerMicrosoft** [comment]
Hi @cihadturhan,
The HealthBotContainerSample uses the WebChat web-based client. You can learn more about customizing the WebChat here: https://github.com/microsoft/BotFramework-WebChat and here: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-webchat-customization?view=azure-bot-service-4.0
