### ISSUE TITLE
Previous chat elements are still clickable even after submitting last event/click/selection. 

### ISSUE THREAD

**Issue by msmarti** [microsoft/HealthBotContainerSample#127]
Previous chat elements are still clickable even after submitting last event/click/selection. 

Users may inadvertently click previous chat elements and change the flow with/out intention and/or - potentially - without awareness. 

It would be great to disable the previous chat elements. I might have found the solution by using:

`document.all.webchat.getElementsByClassName("webchat__basic-transcript__activity webchat__basic-transcript__activity--acknowledged webchat__basic-transcript__activity--read").forEach((item) => { item.style.pointerEvents = "none" });_`

I'm exploring the DOM to understand which Event Listener would be the most appropriate to attach this code to.

Is there something already in the current feature set that would allow me to achieve the same goal?
If not - is there anything in roadmap or how many chances are there that the style/class will change and break this code?

**Comment by GuyBeckerMicrosoft** [comment]
Note that this repo is providing a sample to build a web page that allows users to communicate with the Azure Health Bot, through WebChat. It is not the repo of the Bot Framework WebChat itself.
For customizing the WebChat, see the [WebChat repo](https://github.com/Microsoft/BotFramework-WebChat)
