### ISSUE TITLE
default, non-scenario experience when using container

### ISSUE THREAD

**Issue by kfprugger** [microsoft/HealthBotContainerSample#13]
Hello,

I've updated the App Service with properly named env. variables under Application Settings per the markdown documentation. The webchat renders correctly, but the scenario that I've defined doesn't fire. Is there something I need to do to initiate a scenario (in this case a template from your gallery) in the webchat sample container in this repo?

![image](https://user-images.githubusercontent.com/20729981/76482435-813d5980-63ea-11ea-9419-111425927f1d.png)

Renders this:

![image](https://user-images.githubusercontent.com/20729981/76482498-b053cb00-63ea-11ea-97b7-9c863041f8f1.png)

Any guidance would be appreciated. Thanks!

**Comment by alexsab1** [comment]
Hello @kfprugger, I'm not a contributor but today I had the same question. I found the answer in the commented code of index.js on line 84

https://github.com/microsoft/HealthBotContainerSample/blob/b1125707b9da6ce9f2e884e38daef857c8061e3b/public/index.js#L84

**Comment by alexsab1** [comment]
Also found here: https://docs.microsoft.com/en-us/healthbot/integrations/programmatic_invocation
