### ISSUE TITLE
error: invalid repository URL

### ISSUE THREAD

**Issue by AvidBoo** [microsoft/HealthBotContainerSample#22]
Error with Deploy to Azure ... "deploy.azure.com says  Invalid repository URL" and never completes deployment.

**Comment by cdarling141** [comment]
I've notice the same thing.. you can use https://deploy.azure.com/?repository=https://github.com/Microsoft/HealthBotcontainersample#/form/setup in the meantime

**Comment by AvidBoo** [comment]
Thanks Craig. That new link is worked successfully.

David Booth
Teams: (425) 538-1358  |m: (303) 704-8625 |e: david.booth@microsoft.com<https://mail.microsoft.com/OWA/redir.aspx?C=c34aa9bfa2954ed595de1129f2b06d78&URL=mailto%3adbooth%40microsoft.com> location: Denver, CO

**Comment by AvidBoo** [comment]
It configures correctly. Although, I get 403 Forbidden error when trying to access the web site created https://covid-19avidboo.azurewebsites.net
In the Azure portal for the App Service "Anonymous access is enabled on the App Service app. Users will not be prompted for login."
Any advice to help resolve this issue?

David Booth

Teams: (425) 538-1358  |m: (303) 704-8625 |e: david.booth@microsoft.com<https://mail.microsoft.com/OWA/redir.aspx?C=c34aa9bfa2954ed595de1129f2b06d78&URL=mailto%3adbooth%40microsoft.com> location: Denver, CO

________________________________
From: David Booth
Sent: Wednesday, March 18, 2020 11:04
To: microsoft/HealthBotContainerSample <reply@reply.github.com>; microsoft/HealthBotContainerSample <HealthBotContainerSample@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [microsoft/HealthBotContainerSample] error: invalid repository URL (#22)


Thanks Craig. That new link is worked successfully.



David Booth

Teams: (425) 538-1358  |m: (303) 704-8625 |e: david.booth@microsoft.com<https://mail.microsoft.com/OWA/redir.aspx?C=c34aa9bfa2954ed595de1129f2b06d78&URL=mailto%3adbooth%40microsoft.com> location: Denver, CO

**Comment by barneaoren** [comment]
@AvidBoo have you followed the instructions for plugging in the APP_SECRET and WEBCHAT_SECRET environment variables ?

**Comment by AvidBoo** [comment]
Yes,
I think I have it correct. Used the values from the Health Bot Service  Secrets & Keys.
[cid:image001.png@01D5FDCD.884E8D30]

David Booth
Teams: (425) 538-1358  |m: (303) 704-8625 |e: david.booth@microsoft.com<https://mail.microsoft.com/OWA/redir.aspx?C=c34aa9bfa2954ed595de1129f2b06d78&URL=mailto%3adbooth%40microsoft.com> location: Denver, CO

**Comment by macaulaygidado** [comment]
@AvidBoo did you resolve the error on the webpage yet. It looks like I'm having something similar but mine is 500 Error

**Comment by AvidBoo** [comment]
Not sure.
I was using Edge Canary and tried with GA version of Edge at it worked.

David Booth

**Comment by amir-microsoft** [comment]
We've added an azuredeply.json file in the repo that should resolve the issue. please reopen the issue if you still experiencing any issue
