### ISSUE TITLE
Read me needs one more step

### ISSUE THREAD

**Issue by TheNeumann** [microsoft/HealthBotContainerSample#27]
It would be great in the readme to tell folks to edit the index.js file from App Service Editor to set the trigger action to launch their scenario.  It took me a couple hours to sort out that was why my bot wasn't launching.

http://thewindowsupdate.com/2020/03/16/quick-start-setting-up-your-covid-19-health-bot/

**Comment by amir-microsoft** [comment]
Thanks @MS-Santi , we are looking into your suggestion

**Comment by macaulaygidado** [comment]
@amir-microsoft @TheNeumann I am having a very similar issue where can I get the code as the image in the link above is not clear.

**Comment by TheNeumann** [comment]
It would go here:
![image](https://user-images.githubusercontent.com/28567046/78081525-bcde9a00-737e-11ea-8c28-637c43b7a0d3.png)

**Comment by macaulaygidado** [comment]
Found documentation here too  https://docs.microsoft.com/en-us/healthbot/integrations/programmatic_invocation

**Comment by amir-microsoft** [comment]
readme was updated with scenario triggering instructions at #54
