### ISSUE TITLE
Missing support for user location

### ISSUE THREAD

**Issue by pjirsa** [microsoft/HealthBotContainerSample#28]
Master branch (v3 client) has support to grab user location from browser location services and pass to bot service. This functionality is missing in webchat_v4 version.

**Comment by pjirsa** [comment]
Now resolved for webchat_v4 and webchat_v4_es5 branches.

**Comment by rodrigo-doctari** [comment]
Hi, I followed the steps described in the README file and also on the following document: https://docs.microsoft.com/en-us/healthbot/channels/webchat but I'm not able to get user location. My bot is located here: https://civatest.azurewebsites.net/

Could you help me or put me on the right direction for this kind of support?

Thanks!

**Comment by pjirsa** [comment]
Hi @rodrigo-doctari. If you append `?shareLocation=true` to your URL, it will ask the browser to share its detected lat-long location. This will get passed along as an init parameter to the chat bot client and can be used in your scenario editor.
![image](https://user-images.githubusercontent.com/2207109/81479008-7c2c3900-91e6-11ea-97de-0bfc78772820.png)

**Comment by rodrigo-doctari** [comment]
Thank you Phil! I thought the example allowed me to request location information while in chat and not necessary at the beginning of the conversation, is that possible with this web application?
