### ISSUE TITLE
Mobile devices: Font sizing problems in chromium-based browsers

### ISSUE THREAD

**Issue by MS-Santi** [microsoft/HealthBotContainerSample#31]
On some mobile devices, text is not properly sized and inconsistencies are displayed.
This was uncovered while testing the COVID19_ASSESSMENT scenario on the healthbot.

Solution is to add viewport metadata to ```<HEAD>``` in index.html

```HTML
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
```

**Comment by amir-microsoft** [comment]
Thanks @MS-Santi , we are looking into your suggestion

**Comment by amir-microsoft** [comment]
We've just merged this suggestion to master, thanks @MS-Santi
