### ISSUE TITLE
unable to setup health bot

### ISSUE THREAD

**Issue by itsmnj** [microsoft/HealthBotContainerSample#4]
hi dear, 
i am logging in with my Microsoft partner account to https://healthbot.microsoft.com but i am getting "page not found" error. i am unable to set up any of health bot instance.

can you please help me out to setup health bot?

Thank you.

**Comment by AdamWalkerMicrosoft** [comment]
Hi,

If you have already created a Healthcare Bot from the Azure marketplace, you can access your instance by navigating to https://admin.healthbot.microsoft.com/

If you need to create a new Healthcare Bot you can create it by following steps on the marketplace listing here: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft-hcb.microsofthealthcarebot?tab=Overview

Regards, Adam
