### ISSUE TITLE
Handoff scenario error

### ISSUE THREAD

**Issue by ianblitz** [microsoft/HealthBotContainerSample#40]
Hi,

I have deployed the Health Bot and the HeathBotContainerSample in my tenant.  I have enabled human handoff in the configuration section and am able to "log in" using the sample agent page and see normal user conversations.
![image](https://user-images.githubusercontent.com/17912463/77783319-a060fb80-7026-11ea-86ed-0698da105fba.png)

I have also enabled the "Triage" template conversation in the bot.  However, when I'm supposed to be handed off to a live agent, I get only the response "Handoff scenario error" and a Developer note.
![image](https://user-images.githubusercontent.com/17912463/77783682-4ad91e80-7027-11ea-9c08-dfc406d27b76.png)

Am I missing something?  Is there some way to debug this that I'm not seeing?

**Comment by amir-microsoft** [comment]
Thanks for reporting @ianblitz. we will look into it and update

**Comment by orsharab** [comment]
Hi @ianblitz, it seems like you're trying to begin the handoff scenario with an invalid argument.
If you'll run the scenario from the scenario editor you will probably see the following error in the trace window:
![image](https://user-images.githubusercontent.com/55087830/78166988-59c03680-7456-11ea-97c3-6a18584a37f3.png)
You can also not pass any arguments.
