### ISSUE TITLE
Trigger scenario based on query_string if present

### ISSUE THREAD

**Issue by aaronba-va** [microsoft/HealthBotContainerSample#49]
When performing demos of multiple scenario's it might be useful to switch between them easily.
Currently we would need to either change the existing HealthBotContainer/TokenService or add another HealthBotContainer/TokenService with that triggers a different scenarioId.

If it could be changed in the URL, then demo's could just IFRAME in a different link with unique query_string to the same URL.

**Comment by amir-microsoft** [comment]
Hi @aaronba-va , you actually don't need to change the service for that, you can do one of the following:
1. specify the scenario id in the client code - see line 112 in public/index.js
2. type the following message to the bot in the chat window: "begin <scenario_id>"
