### ISSUE TITLE
Deploy to Azure Quick Link

### ISSUE THREAD

**Issue by gjlisiak** [microsoft/HealthBotContainerSample#50]
Process appears to be broken as of this moment.  I get a "Deployment Error" saying "InvalidTemplateDeployment: The template deployment 'HealthcareBotDemos" is not valid according to the validation procedure... "

**Comment by pjirsa** [comment]
This appears to happen if a previous deployment fails or only partially completes and then the same values are used again when trying to deploy.

I had this same error and was able to resolve by first removing the resource group created as part of the partial deployment. You could also choose different values for site name, resource group, etc.

**Comment by amir-microsoft** [comment]
The deployment error may be related to #51.
Please follow instructions by @pjirsa to resolve
