### ISSUE TITLE
Truncated button text

### ISSUE THREAD

**Issue by pjirsa** [microsoft/HealthBotContainerSample#62]
When viewing chat client on a mobile device or a narrow viewport (aka. inside `<div>` with constrained width) the button choice text becomes truncated.
Including screenshot of issue for CDC triage template:
![image](https://user-images.githubusercontent.com/2207109/78674779-bfbf1a80-78a9-11ea-8277-fab50ce41872.png)

**Comment by amir-microsoft** [comment]
Thanks @pjirsa , we are looking into it

**Comment by pjirsa** [comment]
Resolved by #67
