### ISSUE TITLE
triggeredScenario

### ISSUE THREAD

**Issue by hnabih** [microsoft/HealthBotContainerSample#69]
I am trying to test Covid-19 Assessment Bot.  I followed the instructions as provided in this article:  [https://techcommunity.microsoft.com/t5/healthcare-and-life-sciences/updated-on-4-2-2020-quick-start-setting-up-your-covid-19/ba-p/1230537. ](url)
Changed the scenario id to:
```
`triggeredScenario: {
                                trigger: "{covid19_assessment}",
                                args: {
                                    myVar1: "{custom_arg_1}",
                                    myVar2: "{custom_arg_2}"
                                }
                            }`
```
Do I need to add any args?
You can check it at [https://hnclcovid1.azurewebsites.net/](url)

I would appreciate your assistance.
Thank you

**Comment by AdamWalkerMicrosoft** [comment]
Hi, the scenario ID is a string literal, you don't need the curly braces around it.

**Comment by hnabih** [comment]
Thank you so much Adam.
