### ISSUE TITLE
Deployment Failing

### ISSUE THREAD

**Issue by divurgentuser** [microsoft/HealthBotContainerSample#89]
Hi Team,

Standard deployment failing.

I use a new resource group, East US.

Any idea what's going on?

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    }
  ]
}

**Comment by amir-microsoft** [comment]
Hello, thank you for reaching out!
Seems like a transient issue with pulling the code from github.
Can you try again to deploy?

Thanks

________________________________

**Comment by divurgentuser** [comment]
Hi I tried again, not working. 

It reaches "Validation Passed", but fails on deployment. Same errror message.

I also tried launching from a previous commit, before the ARM template merge. Still no luck. 

Any ideas?

**Comment by amir-microsoft** [comment]
We will look into it.
In the meantime, as a workaround, Which resource in the development is failing?
plan, website or sourceControl?
If it's the sourceControl, you can go to the web app development center, and resync or reconnect it to the github repository

________________________________

**Comment by amir-microsoft** [comment]
We have found the issue is only with webapp running with Linux OS.
We have set the default OS to Windows, and it seems to resolve the issue
