### ISSUE TITLE
when is live_agent_handoff going live?

### ISSUE THREAD

**Issue by divurgentuser** [microsoft/HealthBotContainerSample#98]
Current agent webchat is for "testing purposes only".

Any update on when this might be merged to master and officially supported?

Would be nice if we could login with Active Directory / Microsoft credentials.

**Comment by amir-microsoft** [comment]
Hello @divurgentuser,
The live agent handoff is a core capability of Azure Health Bot, and officially supported by the team.
In addition, the live_agent_handoff branch is officially maintained by the team .
Having said that, the purpose of this repository and branch is to provide a simple reference, for testing and evaluating purpose, for how to embed the Bot in a website.
Each User should implement or integrate his own login flows, and at this point we don't have any plans to change this approach
